name: Luatic Linux Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install clang-format
        run: sudo apt install clang-format-13
      - name: run format test
        run: bash ./clang_format.sh
      - name: check no change
        shell: bash
        run: git diff-files -p --exit-code --diff-filter=ADMR -w
